---
kind: pipeline
type: docker
name: casper-ui-kit-ci

steps:
  - name: install
    image: casperlabs/node-build-u1804
    commands:
      - npm install

  - name: audit
    image: casperlabs/node-build-u1804
    commands:
      - npm run audit

  - name: lint
    image: casperlabs/node-build-u1804
    commands:
      - npm run lint

  - name: style check
    image: casperlabs/node-build-u1804
    commands:
      - npm run style:check

  - name: build storybook
    image: casperlabs/node-build-u1804
    commands:
      - npm run build-storybook

  - name: npm test
    image: casperlabs/node-build-u1804
    commands:
      - npm run test

trigger:
  branch:
    - dev
    - "feat-*"
    - "release-*"
  event:
    include:
      - pull_request
      - push
    exclude:
      - tag
      - cron

---
kind: pipeline
type: docker
name: nightly-testing

steps:
  - name: npm install
    image: casperlabs/node-build-u1804
    commands:
      - npm install

  - name: npm test
    image: casperlabs/node-build-u1804
    commands:
      - npm run test

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_nightly
      template:
        - |
          Casper-UI-Kit Nightly Test Status: *{{ uppercasefirst build.status }}*
          Repo: {{ repo.name }}
          Author: {{ build.author }}
          Drone Build: <{{ build.link }}|#{{ build.number }}>
          Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
    when:
      status:
        - failure
        - success

trigger:
  cron: [nightly-tests-cron]
